import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Nunito_Sans } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito_Sans({
  subsets: ["latin"],
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${nunito.className}`}>
        {children}
      </body>
    </html>
  );
}
